### ISSUE TITLE
OpenTelemetry Specification 1.34.0 Release Epic

### ISSUE THREAD

**Issue by bobstrecansky** [open-telemetry/opentelemetry-php#1334]
The OpenTelemetry Specification Release 1.34.0 happened yesterday:
https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.34.0

We need to add in the changes from the specification to our repository.  Subsequent issues are listed below for each of them, this issue is just be a meta placeholder for all of the issues created.

- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1323
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1324
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1325
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1326
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1327
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1328
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1329
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1330
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1331
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1332
- [x] https://github.com/open-telemetry/opentelemetry-php/issues/1333
