### ISSUE TITLE
[meta] Documentation for OpenTelemetry PHP

### ISSUE THREAD

**Issue by tidal** [open-telemetry/opentelemetry-php#758]
Meta issue for documentations regarding OpenTelemetry PHP.

- [ ] Add READMEs to individual packages
  - [x] https://github.com/open-telemetry/opentelemetry-php/issues/770
  - [x] https://github.com/open-telemetry/opentelemetry-php/issues/772
  - [x] https://github.com/open-telemetry/opentelemetry-php/issues/771
  - [x] https://github.com/open-telemetry/opentelemetry-php/issues/773
  - [x] https://github.com/open-telemetry/opentelemetry-php/issues/774
