### ISSUE TITLE
[META] php 8.2 support

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#826]
Issues to be resolved to enable opentelemetry-php to work with php 8.2:

- [x] ${var} in strings https://github.com/open-telemetry/opentelemetry-php/pull/810
- [x] protobuf (native) https://github.com/protocolbuffers/protobuf/pull/10594
- [x] protobuf (extension) (dynamic properties) - extension v3.20.1+ is ok
- [x] grpc (dynamic properties) https://github.com/grpc/grpc/pull/30997
- [x] grpc released (v1.51.0)
- [ ] protobuf released (should be in v3.22.0)

**Comment by bobstrecansky** [comment]
All the PRs are in for this, we are just waiting on Google support.  I'm going to follow up with them.

**Comment by bobstrecansky** [comment]
I've bumped our Google support rep today; waiting to hear back from them.

**Comment by brettmc** [comment]
gRPC and protobuf PRs have been merged, now to wait for them to be included in releases.

**Comment by bobstrecansky** [comment]
I'm going to ping our google rep about a release of https://github.com/protocolbuffers/protobuf

**Comment by brettmc** [comment]
I'm going to close this, since the only outstanding issue (protobuf) shouldn't affect us (since we strongly encourage using the extension).
One last thing to note, is that php-cs-fixer isn't certified against 8.2, and until it is `make style` will complain.
