### ISSUE TITLE
replace/remove "meta packages" in packagist

### ISSUE THREAD

**Issue by brettmc** [open-telemetry/opentelemetry-php#929]
We currently publish `open-telemetry/opentelemetry`, `open-telemetry/opentelemetry-php-contrib` `open-telemetry/sdk-contrib` which are based on our monorepo.
Since we no longer tag the monorepo, these don't make sense (except possibly for `dev-main`). We can't version them consistently with the individual packages because we are tagging those all independently, and I think it will lead to confusion.

We could possibly create a [meta-package](https://getcomposer.org/doc/04-schema.md#type) to replace each, but we would still have the same versioning confusion...

My suggestion is to abandon both packages, and suggest `open-telemetry/sdk` as a replacement for `open-telemetry/opentelemetry`. I don't think there is a sensible replacement for either of the `-contrib` packages.

- [x] open-telemetry/sdk-contrib
- [x] open-telemetry/opentelemetry-php-contrib
- [x] open-telemetry/opentelemetry

**Comment by bobstrecansky** [comment]
We should ask about this in the #otel-maintainers repo

**Comment by brettmc** [comment]
agreed in SIG to abandon these packages in packagist.

**Comment by brettmc** [comment]
I have marked those repos as "abandoned" in packagist, and added suggested replacements:
`opentelemetry` -> `sdk`
`sdk-contrib` -> `exporter-*`
`opentelemetry-php-contrib` -> -nothing-
